[env:rpipico2]
platform     = https://github.com/maxgerhardt/platform-raspberrypi.git
board        = rpipico2 ; rpipico2w for pico with WLAN
framework    = arduino
board_build.core = earlephilhower
monitor_speed = 115200
monitor_echo   = yes        ; eingetippte Zeichen werden angezeigt
monitor_eol    = LF

; if with flash option, activate thefollowing option to acquire space on the flash
; board_build.filesystem_size = 2048k
 
build_flags =
    -O2
    -DPICO_USE_STACK_GUARDS=1
    -std=gnu++17
    -I.

build_src_dir = .
build_src_filter = +<*.cpp> -<.git/>
